### PR TITLE
chore: set up renovate for dependency management

### PR DESCRIPTION
**Pull request by onedr0p**
Hi again 👋🏼 

Here is a PR to the start of something great I hope 😄  [Renovate](https://github.com/renovatebot/renovate) is a amazing tool for dependency management and keeping packages up-to-date by open PRs for review. There are other alternatives like GitHubs dependabot but I find Renovate to be way more configurable. Renovate can handle a whole ton of [datasources](https://docs.renovatebot.com/modules/datasource/).

To get started, merge this PR then head over to https://github.com/apps/renovate and configure your repo to use it. You should start to see some PRs roll in for updates if any are found.

I can help you tweak this settings further or answer any questions you may have, I've been using this tool for years.

### CODE REVIEW

**Comment by zoriya** [comment]
I disabled dependabot because the front uses both expo and nextjs in a monorepo setup and every common package needs to be at **exactly** the sane version between the two projects. Does the same issue exist with renovate?

**Comment by onedr0p** [comment]
Yes those can be grouped to be the same version.  It will take some tweaking of the config so I would suggest to enable it and tweak it to your needs.

You can see the preset groups and the expressions how they are group, or create your own groups.
https://docs.renovatebot.com/presets-group/

**Comment by onedr0p** [comment]
@zoriya updated to ignore the front dir.

**Comment by zoriya** [comment]
Thanks!

**Pull request merged**
